### PR TITLE
saving user name

### PR DESCRIPTION
**Pull request by heron2014**
Related to [51](https://github.com/FAC-GM/gm-magic/issues/51)

@nelsonic can you have look at this PR? thanks.

### CODE REVIEW

**Comment by nelsonic** [comment]
Looks good.
There are a few indentations you can tidy up.
Are you going to re-publish the extension now?

**Comment by heron2014** [comment]
thansk @nelsonic and sorry for late response! I will publish tomorrow, I can do small PR with cleaned up code or I will do that with the next coming PR?

**Comment by nelsonic** [comment]
Cleanup in the next PR. the indentation does not affect functionality.

**Comment by heron2014** [comment]
Ok, thanks @nelsonic

**Pull request merged**
